install:
 - pip install selenium pytest pytest-xdist sauceclient unittest-data-provider

addons:
  sauce_connect: true

language: python

python:
  - "2.7"
script: "py.test -n2 --boxed ./twitter-test/tests/login.py ./twitter-test/tests/post_tweet.py"
